DATA:
  IMG_SIZE: 384
  TRANSFORM_TYPE: easy

MODEL:
  TYPE: swin
  NAME: swin_large_patch4_window12_384_22kto1k_finetune
  PRETRAINED: /comp_robot/workspace/chenyihao/SwinLips_Lalpha_2/output/swin_plus_large_patch4_window7_224_22k/large_plus_22k_30_beta_2_0998/ckpt_epoch_28.pth
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 288
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TRAIN:
  OPTIMIZER:
    NAME: SGD
    MOMENTUM: 0.9

  EPOCHS: 8
  WEIGHT_DECAY: 0.0
  BASE_LR: 3e-02
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False
AUG:
  MIXUP: 0.1
  CUTMIX: 0.0
  CUTMIX_MINMAX: None
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.0