DATA:
  IMG_SIZE: 384

MODEL:
  TYPE: swin
  NAME: swin_large_patch4_window12_384_22kto1k_finetune
  PRETRAINED: /comp_robot/workspace/chenyihao/SwinLips_Lalpha_2/output/swin_plus_large_patch4_window7_224_22k/large_plus_22k_30_beta_2_0998/ckpt_epoch_28.pth
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 288
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
  OPTIMIZER:
    BETAS: (0.9, 0.998)
TEST:
  CROP: False